config/routes.rb
Rails.application.routes.draw do
  
  root to: "expenses#index"

  resources :expenses
  resources :tags, constraints: {format: 'json'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clan.rb
class Clan
    include Mongoid::Document
    include Mongoid::Timestamps
    include Mongoid::Includes
  
    field :name, type: String
    field :description, type: String
    field :status, type: Integer
    
    has_many :expenses
    has_many :users
    has_many :tags  

end

app/models/expense.rb
class Expense
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Includes

  field :name, type: String
  field :description, type: String
  field :value, type: Float
  field :status, type: Integer
  field :date, type: Date
  field :tags, type: Array

  belongs_to :clan
  belongs_to :user
  
  scope :filter_month, ->(date_filter, current_clan) {where date:( date_filter.beginning_of_month .. date_filter.end_of_month), clan: current_clan}


end

app/models/tag.rb
class Tag
  include Mongoid::Document

  field :tag, type: String
  
  belongs_to :clan
  belongs_to :user

end

app/models/user.rb
class User 
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Includes

  field :name, type: String
  field :email, type: String
  field :status, type: Integer
    
  has_many :expenses
  has_many :tags

  belongs_to :clan

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :find_logged_user

    private
    def find_logged_user
        @user = User.first
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.where(clan: @user.clan)
    @expenses_summary = {last: Expense.filter_month(Date.today.last_month, @user.clan), 
                         current: Expense.filter_month(Date.today, @user.clan), 
                         next: Expense.filter_month(Date.today.next_month, @user.clan)}
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:name, :description, :value, :status, :date)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    # GET /tags
    # GET /tas.json
    def index
        all_user_tags =[]
        @user.clan.users.each do |user|
            user.tags.each do |tag| 
                all_user_tags.push({text: tag.tag, id: tag.id.to_s})
            end
        end
        render json: all_user_tags
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_with(model: expense, local: true) do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expenses</h1>
<modal :show='show' @close="show=false"></modal>
<button type="button" class="btn btn-info btn-lg" @click="show = true">Open Modal</button>

  <sum :expenses='<%=@expenses_summary.to_json%>'></sum>
  
  <div class="row">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Value</th>
          <th>Status</th>
          <th>Date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @expenses.each do |expense| %>
          <tr>
            <td><%= expense.name %></td>
            <td><%= expense.description %></td>
            <td><%= expense.value %></td>
            <td><%= expense.status %></td>
            <td><%= expense.date %></td>
            <td><%= link_to 'Show', expense %></td>
            <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
            <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
  </div>
<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @expense.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @expense.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @expense.value %>
</p>

<p>
  <strong>Status:</strong>
  <%= @expense.status %>
</p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application'%>
  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Fixed navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>
    <div class="container" data-behavior="vue">
    <%= yield %>
    </div>
  </body>
</html>